### Задача №1 «Треугольник с максимальным периметром»

Массив A состоит из целых положительных чисел ­ длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью ­ функция возвращает 0

In [14]:
import numpy as np
 
np.random.seed(12) 
A = np.random.randint(1, 10000, size=(3, 6)) # массив случайных длинн строн треугольника
rMax = np.argmax(A, axis=1) # индексы максимумов по строкам
 
sMax = 0 # переменная для максимума
b = 0 # индекс для максимума
 
print('Исходные данные:\n' + str(A))
 
for i in range(len(A)):
    # поставить максимальный элемент в первую ячейку строки
    if rMax[i] != 0:
        A[i,0], A[i, rMax[i]] = A[i, rMax[i]], A[i,0]
        
for i in range(len(A)):
    if (A[i,0]) < (A[i,1] + A[i,2]): # треугольник существует
        if (A[i,0] + A[i,1] + A[i,2]) > sMax: # поиск максимума
            sMax, b = A[i,0] + A[i,1] + A[i,2], i
            
if b == 0:
    print('Такого треугольника не существует')
else:
    print('У треугольника со сторонами', A[b,0], A[b,1], A[b,2], 'максимальный периметр', sMax)

Исходные данные:
[[5788 9607 3326 7410 3715 9476]
 [ 279 8242 3726 4570 8611 8652]
 [9847 5195 1129 3277 4179 8282]]
У треугольника со сторонами 8652 8242 3726 максимальный периметр 20620


### Задача №2 «Максимальное число»

Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы вместе они образовали максимально возможное число. Замечание: Результат может быть очень большим числом, поэтому представьте его как string, а не integer

In [17]:
def mNum(arr):
    def is_a_big_than_b(a, b):
        ab = int(str(a) + str(b))
        ba = int(str(b) + str(a))
        if ab > ba:
            return True
        else:
            return False
    
    def sortArr(arr):
        for i in range(len(arr) - 1):
            big = i
            for j in range(i + 1, len(arr)):
                if not is_a_big_than_b(arr[big], arr[j]):
                    big = j
            arr[i], arr[big] = arr[big], arr[i]
    
    sortArr(arr)
    return ''.join(str(e) for e in arr)


print(mNum([10,2]))
print(mNum([3,30,34,5,9]))
print(mNum([1]))
print(mNum([0,1]))

210
9534330
1
10


### Задача №3 «Сортировка диагоналей в матрице»

Дана матрица mat размером m * n, значения ­ целочисленные. Напишите функцию, сортирующую каждую диагональ матрицы по возрастанию и возвращающую получившуюся матрицу.

In [12]:
def sortMat(matrix):
    def comp(matrix, i ,j):
        if i==0 or j==0:
            return
        try:
            if matrix[i][j]<matrix[i-1][j-1]:
                matrix[i][j],matrix[i-1][j-1]=matrix[i-1][j-1],matrix[i][j]
                return(comp(matrix,i+1,j+1))
        except IndexError:
            return
    for i in range(len(matrix)-1,-1,-1):
        for j in range(0, len(matrix[i]),1):
            comp(matrix,i,j)
    return matrix
print(sortMat([[3, 3, 1, 1], [2, 2, 1, 2], [1, 1, 1, 2]]))
print(sortMat([[11, 25, 66, 1, 69, 7], [23, 55, 17, 45, 15, 52], [75, 31, 36,44, 58, 8], [22, 27, 33, 25, 68, 4], [84, 28, 14, 11, 5, 50]]))

[[1, 1, 1, 1], [1, 2, 2, 2], [1, 2, 3, 3]]
[[5, 17, 4, 1, 52, 7], [11, 11, 25, 45, 8, 69], [14, 23, 25, 44, 58, 15], [22, 27, 31, 36, 50, 66], [84, 28, 75, 33, 55, 68]]


## Работа со строками

### Задача 1

Даны две строки: s1 и s2 с одинаковым размером, проверьте, может ли некоторая перестановка строки s1 “победить” некоторую перестановку строки s2 или наоборот. Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y [i] (в алфавитном порядке) для всех i от 0 до n-1

In [4]:
def check(s1, s2):
    s1 = sorted(s1)
    s2 = sorted(s2)
    flag1 = True
    flag2 = True
    for i in range(len(s1)):
        if s1[i] > s2[i]:
            flag2 = False
        if s2[i] > s1[i]:
            flag1 = False
    return flag1 or flag2

s1 = "abc"
s2 = "cda"
print(check(s1, s2))

True


### Задача 2

Дана строка s, вернуть самую длинную полиндромную подстроку в s.

In [16]:
def Palindromes(s):
    s_rev = s[::-1]
    return s_rev == s
def Longest_Palindrome(s):
    max_len = 1
    Max_pal = s[0]
    for i in range(len(s) - 1):
        for j in range (i+1, len(s)):
            if Palindromes(s[i:j]) and len(s[i:j]) > max_len:
                max_len = len(s[i:j])
                Max_pal = s[i:j]
    return Max_pal

s = "abb2x2MADAM2xr"
print(Longest_Palindrome(s))

x2MADAM2x


### Задача 3

Вернуть количество отдельных непустых подстрок текста, которые могут быть записаны как конкатенация некоторой строки с самой собой (т.е. она может быть записана, как a + a, где a - некоторая строка)

In [6]:
s = input("Введите строку: ")
sb = input("Введите подстроку: ")
results = 0
sub_len = len(sb)
for i in range(len(s)):
    if s[i:i+sub_len] == sb:
        results += 1
print(results)

Введите строку: ababababab
Введите подстроку: ab
5


## 27 февраля 

### Задача 1

В Тридевятом Царстве уже много лет как установилась конституционная монархия. В парламент Тридевятого царства входят 26 партий, обозначаемых строчными буквами английского алфавита от «a» до «z». Заседание парламента в соответствии с регламентом проходит по следующей схеме:

* В начале заседания никаких законопроектов на повестке дня не стоит.
* Любая партия (в том числе и та, которая внесла текущий законопроект) в любой момент времени может внести на обсуждение новый законопроект.
* При вносе партией нового законопроекта обсуждение предыдущего приостанавливается и начинается обсуждение нового. После того, как парламентарии голосуют за новый законопроект, обсуждение законопроекта, прерванного им, продолжается.
* Дискуссия по любому законопроекту обязана завершиться голосованием по этому законопроекту.
* В конце заседания не должно остаться внесённых законопроектов, дискуссия по которым не завершена.


Вам дана запись о событиях на сессии парламента. Каждое событие является либо внесением нового законопроекта, либо голосованием за какой-то законопроект, причём в обоих случаях известен номер партии, этот законопроект предложившей. События даны в том порядке, в котором они происходили. Проверьте, может ли данная запись о событиях соответствовать какому-либо заседанию, удовлетворяющему порядку проведения, описанному выше.

**Входные данные**

Первая строка входных данных содержит одно целое число K – количество строк в записи сессии (1 ≤ K ≤ 1000). Каждая строка соответствует одному из двух событий:

Add x – партия x внесла на голосование законопроект.
Vote x – прошло голосование за документ, внесённый партией x.

Здесь x – строчная буква английского алфавита от «a» до «z», задающая партию.

**Вывод**

Выведите «Yes», если существует корректный порядок проведения заседания, который мог привести к такой записи, и «No», если ни при каком корректном порядке проведения заседания данная запись появиться не могла.

In [9]:
def check(events):
    stack = []
    for e in events:
        cmd, party = e.split()
        if cmd == "Add":
            stack.append(party)
        elif stack.pop() != party:
            return "No"
    return "Yes" if len(stack) == 0 else "No"

assert check(["Add x", "Add y", "Vote y", "Vote x"]) == "Yes"
assert check(["Add x", "Add x", "Vote y", "Vote x"]) == "No"
assert check(["Add x", "Add y"]) == "No"
assert check(["Add x", "Vote x"]) == "Yes"

### Задача 2. Правильный подмногоугольник

Задан правильный N-угольник. Требуется выбрать наименьшее количество его вершин, которые также образуют правильный многоугольник.

**Входные данные**

Входные данные содержат одно целое число N (3 ≤ N ≤ 10^12).

**Вывод**

Выведите одно число — наименьшее количество вершин заданного многоугольника, которые образуют правильный многоугольник

In [8]:
def subpolygon(N):
    for i in range(3, int(N**.5)+1):  # так максимум проверок 10^6  
        if N % i == 0: return i
    if N > 4 and N % 2 == 0:
        # многоугольника из 2 вершин не существует
        # но второй множитель явно больше 2 (для N > 4), поэтому если ничего из цикла не подошло
        # то это число нам подходит
        return N / 2
    return N

assert subpolygon(3) == 3
assert subpolygon(4) == 4
assert subpolygon(8) == 4
assert subpolygon(9) == 3
assert subpolygon(10) == 5
assert subpolygon(11) == 11
assert subpolygon(16) == 4
assert subpolygon(5942430146) == 2971215073

### Задача 3

На форуме, на котором обсуждаются задачи олимпиад по информатике, ввели следующий аналог капчи. Участнику выдаётся строка из N десятичных цифр (без ведущих нулей). В качестве ответа требуется ввести такое основание системы счисления B, что в этой системе счисления выданная запись будет соответствовать составному числу (назовем его D), а также число X, большее 1 и меньшее D, являющееся делителем D.

При этом B и X не должны превосходить 10^9. По заданной строке десятичных цифр найдите любую пару чисел B и X, удовлетворяющую ограничениям, или ответьте, что решения в заданных ограничениях не существует.

**Входные данные**

Входные данные состоят из непустой строки длиной до 3 ⋅ 10^6 символов, составленной из цифр от 0 до 9 и не начинающейся с 0.

**Вывод**

Если решение существует, выведите два числа – основание системы счисления B и делитель X, записанные в десятичной системе счисления. Оба числа должны удовлетворять ограничениям 2 ≤ B, X ≤ 10^9. Если решения не существует, выведите –1.

In [10]:
def captcha(s):
    if len(s) == 1:
        res = [0,0,0,2,0,2,0,2,3][int(s)-1]
        if res:
            return 10, res
        return -1
    S = sum(map(int, s))
    if S == 1:
        return 10, 2
    return S + 1, S

assert captcha('5') == -1
assert captcha('8') == (10, 2)
assert captcha('10') == (10, 2)
assert captcha("19") == (11, 10)